travis: known_failures: add test__issue6.py
It often fails with:

master ~/work/gevent $ python greentest/test__issue6.py
Traceback (most recent call last):
  File "greentest/test__issue6.py", line 11, in <module>
    assert err == '', (out, err, code)
AssertionError: ('11 chars.\n', 'Unhandled exception in thread started by \nsys.excepthook is missing\nlost sys.stderr\n', 0)